### ISSUE TITLE
Custom JsonMapper with Camel

### ISSUE THREAD

**Issue by jeremyross** [jam01/xtrasonnet#12]
Hi,

How can I provide a custom JsonMapper instance to camel-xtrasonnet?

**Comment by jam01** [comment]
Ah, this is currently not supported.

I could add a solution like https://camel.apache.org/components/3.20.x/languages/groovy-language.html#_customizing_groovy_shell

Were you thinking of something different?

**Comment by jeremyross** [comment]
Yeah, it looks it looks like that's similar to how the Jackson data format allows you to refer to an [existing ObjectMapper](https://camel.apache.org/components/3.14.x/dataformats/json-jackson-dataformat.html#_jackson_options) in the registry. Or maybe allow providing a `DefaultJavaPlugin`? Not familiar enough with the xtrasonnet api to know if there's any value in this, now or in the future.

**Comment by jam01** [comment]
#13  should work -- I think keeping a similar solution to the existing ObjectMapper registry lookup should feel "idiomatic" though perhaps plugins in the registry could be still added later.

If it looks to good, I'll merge and release 0.5.2 with this.

I tried to also make it work with ObjectMapper so developers wouldn't have to possibly register both, but couldn't find a way to go from ObjectMapper to JsonMapper, and as far as I understand JsonMapper is the preferred class now.

**Comment by jeremyross** [comment]
JsonMapper is probably fine. But it may be better to allow users to specify the JsonMapper by name. If they happen to have another JsonMapper in the registry for another reason, they may not intend for it to be used for xtrasonnet.

**Comment by jam01** [comment]
0.5.2 is out

**Comment by jeremyross** [comment]
Thanks. This will work, but it's more idomatic to create an option that allows the user to specify the name of the registry key under which the JsonMapper can be found.

**Comment by jam01** [comment]
Oh ok I see. Do other components do something similar? So I name the option similarly

**Comment by jeremyross** [comment]
Yeah, check out the JSON Jackson data format's [objectMapper option](https://camel.apache.org/components/3.14.x/dataformats/json-jackson-dataformat.html#_jackson_options).
